// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kafkamgmt/v1/queue_service.proto

package kafkamgmtv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAttributes) Reset() {
	*x = MessageAttributes{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAttributes) ProtoMessage() {}

func (x *MessageAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAttributes.ProtoReflect.Descriptor instead.
func (*MessageAttributes) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{0}
}

func (x *MessageAttributes) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SendMessageRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	QueueName              string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageBody            []byte                 `protobuf:"bytes,2,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	MessageAttributes      *MessageAttributes     `protobuf:"bytes,3,opt,name=message_attributes,json=messageAttributes,proto3" json:"message_attributes,omitempty"`
	MessageGroupId         string                 `protobuf:"bytes,4,opt,name=message_group_id,json=messageGroupId,proto3" json:"message_group_id,omitempty"`                         // FIFO only
	MessageDeduplicationId string                 `protobuf:"bytes,5,opt,name=message_deduplication_id,json=messageDeduplicationId,proto3" json:"message_deduplication_id,omitempty"` // FIFO only
	DelaySeconds           int32                  `protobuf:"varint,6,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *SendMessageRequest) GetMessageBody() []byte {
	if x != nil {
		return x.MessageBody
	}
	return nil
}

func (x *SendMessageRequest) GetMessageAttributes() *MessageAttributes {
	if x != nil {
		return x.MessageAttributes
	}
	return nil
}

func (x *SendMessageRequest) GetMessageGroupId() string {
	if x != nil {
		return x.MessageGroupId
	}
	return ""
}

func (x *SendMessageRequest) GetMessageDeduplicationId() string {
	if x != nil {
		return x.MessageDeduplicationId
	}
	return ""
}

func (x *SendMessageRequest) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

type SendMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SequenceNumber string                 `protobuf:"bytes,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // FIFO only
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetSequenceNumber() string {
	if x != nil {
		return x.SequenceNumber
	}
	return ""
}

type SendMessageBatchEntry struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageBody            []byte                 `protobuf:"bytes,2,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	MessageAttributes      *MessageAttributes     `protobuf:"bytes,3,opt,name=message_attributes,json=messageAttributes,proto3" json:"message_attributes,omitempty"`
	MessageGroupId         string                 `protobuf:"bytes,4,opt,name=message_group_id,json=messageGroupId,proto3" json:"message_group_id,omitempty"`
	MessageDeduplicationId string                 `protobuf:"bytes,5,opt,name=message_deduplication_id,json=messageDeduplicationId,proto3" json:"message_deduplication_id,omitempty"`
	DelaySeconds           int32                  `protobuf:"varint,6,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SendMessageBatchEntry) Reset() {
	*x = SendMessageBatchEntry{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageBatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageBatchEntry) ProtoMessage() {}

func (x *SendMessageBatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageBatchEntry.ProtoReflect.Descriptor instead.
func (*SendMessageBatchEntry) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageBatchEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendMessageBatchEntry) GetMessageBody() []byte {
	if x != nil {
		return x.MessageBody
	}
	return nil
}

func (x *SendMessageBatchEntry) GetMessageAttributes() *MessageAttributes {
	if x != nil {
		return x.MessageAttributes
	}
	return nil
}

func (x *SendMessageBatchEntry) GetMessageGroupId() string {
	if x != nil {
		return x.MessageGroupId
	}
	return ""
}

func (x *SendMessageBatchEntry) GetMessageDeduplicationId() string {
	if x != nil {
		return x.MessageDeduplicationId
	}
	return ""
}

func (x *SendMessageBatchEntry) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

type SendMessageBatchRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	QueueName     string                   `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Entries       []*SendMessageBatchEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageBatchRequest) Reset() {
	*x = SendMessageBatchRequest{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageBatchRequest) ProtoMessage() {}

func (x *SendMessageBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageBatchRequest.ProtoReflect.Descriptor instead.
func (*SendMessageBatchRequest) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageBatchRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *SendMessageBatchRequest) GetEntries() []*SendMessageBatchEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BatchResultEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResultEntry) Reset() {
	*x = BatchResultEntry{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResultEntry) ProtoMessage() {}

func (x *BatchResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResultEntry.ProtoReflect.Descriptor instead.
func (*BatchResultEntry) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchResultEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BatchResultEntry) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *BatchResultEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendMessageBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    []*BatchResultEntry    `protobuf:"bytes,1,rep,name=successful,proto3" json:"successful,omitempty"`
	Failed        []*BatchResultEntry    `protobuf:"bytes,2,rep,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageBatchResponse) Reset() {
	*x = SendMessageBatchResponse{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageBatchResponse) ProtoMessage() {}

func (x *SendMessageBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageBatchResponse.ProtoReflect.Descriptor instead.
func (*SendMessageBatchResponse) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageBatchResponse) GetSuccessful() []*BatchResultEntry {
	if x != nil {
		return x.Successful
	}
	return nil
}

func (x *SendMessageBatchResponse) GetFailed() []*BatchResultEntry {
	if x != nil {
		return x.Failed
	}
	return nil
}

type ReceiveMessageRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	QueueName                string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MaxNumberOfMessages      int32                  `protobuf:"varint,2,opt,name=max_number_of_messages,json=maxNumberOfMessages,proto3" json:"max_number_of_messages,omitempty"`              // <= 10
	WaitTimeSeconds          int32                  `protobuf:"varint,3,opt,name=wait_time_seconds,json=waitTimeSeconds,proto3" json:"wait_time_seconds,omitempty"`                            // 0-20, long-poll
	VisibilityTimeoutSeconds int32                  `protobuf:"varint,4,opt,name=visibility_timeout_seconds,json=visibilityTimeoutSeconds,proto3" json:"visibility_timeout_seconds,omitempty"` // override
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ReceiveMessageRequest) Reset() {
	*x = ReceiveMessageRequest{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessageRequest) ProtoMessage() {}

func (x *ReceiveMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessageRequest.ProtoReflect.Descriptor instead.
func (*ReceiveMessageRequest) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReceiveMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *ReceiveMessageRequest) GetMaxNumberOfMessages() int32 {
	if x != nil {
		return x.MaxNumberOfMessages
	}
	return 0
}

func (x *ReceiveMessageRequest) GetWaitTimeSeconds() int32 {
	if x != nil {
		return x.WaitTimeSeconds
	}
	return 0
}

func (x *ReceiveMessageRequest) GetVisibilityTimeoutSeconds() int32 {
	if x != nil {
		return x.VisibilityTimeoutSeconds
	}
	return 0
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReceiptHandle  string                 `protobuf:"bytes,2,opt,name=receipt_handle,json=receiptHandle,proto3" json:"receipt_handle,omitempty"`
	Body           []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Attributes     *MessageAttributes     `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	ReceiveCount   int32                  `protobuf:"varint,5,opt,name=receive_count,json=receiveCount,proto3" json:"receive_count,omitempty"`
	MessageGroupId string                 `protobuf:"bytes,6,opt,name=message_group_id,json=messageGroupId,proto3" json:"message_group_id,omitempty"`
	EnqueuedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{8}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetAttributes() *MessageAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Message) GetReceiveCount() int32 {
	if x != nil {
		return x.ReceiveCount
	}
	return 0
}

func (x *Message) GetMessageGroupId() string {
	if x != nil {
		return x.MessageGroupId
	}
	return ""
}

func (x *Message) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

type ReceiveMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessageResponse) Reset() {
	*x = ReceiveMessageResponse{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessageResponse) ProtoMessage() {}

func (x *ReceiveMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessageResponse.ProtoReflect.Descriptor instead.
func (*ReceiveMessageResponse) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiveMessageResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ReceiptHandle string                 `protobuf:"bytes,2,opt,name=receipt_handle,json=receiptHandle,proto3" json:"receipt_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *DeleteMessageRequest) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{11}
}

type DeleteMessageBatchEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReceiptHandle string                 `protobuf:"bytes,2,opt,name=receipt_handle,json=receiptHandle,proto3" json:"receipt_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageBatchEntry) Reset() {
	*x = DeleteMessageBatchEntry{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageBatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageBatchEntry) ProtoMessage() {}

func (x *DeleteMessageBatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageBatchEntry.ProtoReflect.Descriptor instead.
func (*DeleteMessageBatchEntry) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMessageBatchEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteMessageBatchEntry) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

type DeleteMessageBatchRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	QueueName     string                     `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Entries       []*DeleteMessageBatchEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageBatchRequest) Reset() {
	*x = DeleteMessageBatchRequest{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageBatchRequest) ProtoMessage() {}

func (x *DeleteMessageBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageBatchRequest) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMessageBatchRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *DeleteMessageBatchRequest) GetEntries() []*DeleteMessageBatchEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DeleteMessageBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    []*BatchResultEntry    `protobuf:"bytes,1,rep,name=successful,proto3" json:"successful,omitempty"`
	Failed        []*BatchResultEntry    `protobuf:"bytes,2,rep,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageBatchResponse) Reset() {
	*x = DeleteMessageBatchResponse{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageBatchResponse) ProtoMessage() {}

func (x *DeleteMessageBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageBatchResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageBatchResponse) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteMessageBatchResponse) GetSuccessful() []*BatchResultEntry {
	if x != nil {
		return x.Successful
	}
	return nil
}

func (x *DeleteMessageBatchResponse) GetFailed() []*BatchResultEntry {
	if x != nil {
		return x.Failed
	}
	return nil
}

type ChangeMessageVisibilityRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	QueueName                string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ReceiptHandle            string                 `protobuf:"bytes,2,opt,name=receipt_handle,json=receiptHandle,proto3" json:"receipt_handle,omitempty"`
	VisibilityTimeoutSeconds int32                  `protobuf:"varint,3,opt,name=visibility_timeout_seconds,json=visibilityTimeoutSeconds,proto3" json:"visibility_timeout_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ChangeMessageVisibilityRequest) Reset() {
	*x = ChangeMessageVisibilityRequest{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMessageVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMessageVisibilityRequest) ProtoMessage() {}

func (x *ChangeMessageVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMessageVisibilityRequest.ProtoReflect.Descriptor instead.
func (*ChangeMessageVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{15}
}

func (x *ChangeMessageVisibilityRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *ChangeMessageVisibilityRequest) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

func (x *ChangeMessageVisibilityRequest) GetVisibilityTimeoutSeconds() int32 {
	if x != nil {
		return x.VisibilityTimeoutSeconds
	}
	return 0
}

type ChangeMessageVisibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMessageVisibilityResponse) Reset() {
	*x = ChangeMessageVisibilityResponse{}
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMessageVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMessageVisibilityResponse) ProtoMessage() {}

func (x *ChangeMessageVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafkamgmt_v1_queue_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMessageVisibilityResponse.ProtoReflect.Descriptor instead.
func (*ChangeMessageVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_kafkamgmt_v1_queue_service_proto_rawDescGZIP(), []int{16}
}

var File_kafkamgmt_v1_queue_service_proto protoreflect.FileDescriptor

const file_kafkamgmt_v1_queue_service_proto_rawDesc = "" +
	"\n" +
	" kafkamgmt/v1/queue_service.proto\x12\fkafkamgmt.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x11MessageAttributes\x12C\n" +
	"\x06values\x18\x01 \x03(\v2+.kafkamgmt.v1.MessageAttributes.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x02\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12!\n" +
	"\fmessage_body\x18\x02 \x01(\fR\vmessageBody\x12N\n" +
	"\x12message_attributes\x18\x03 \x01(\v2\x1f.kafkamgmt.v1.MessageAttributesR\x11messageAttributes\x12(\n" +
	"\x10message_group_id\x18\x04 \x01(\tR\x0emessageGroupId\x128\n" +
	"\x18message_deduplication_id\x18\x05 \x01(\tR\x16messageDeduplicationId\x12#\n" +
	"\rdelay_seconds\x18\x06 \x01(\x05R\fdelaySeconds\"]\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\tR\x0esequenceNumber\"\xa3\x02\n" +
	"\x15SendMessageBatchEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fmessage_body\x18\x02 \x01(\fR\vmessageBody\x12N\n" +
	"\x12message_attributes\x18\x03 \x01(\v2\x1f.kafkamgmt.v1.MessageAttributesR\x11messageAttributes\x12(\n" +
	"\x10message_group_id\x18\x04 \x01(\tR\x0emessageGroupId\x128\n" +
	"\x18message_deduplication_id\x18\x05 \x01(\tR\x16messageDeduplicationId\x12#\n" +
	"\rdelay_seconds\x18\x06 \x01(\x05R\fdelaySeconds\"w\n" +
	"\x17SendMessageBatchRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12=\n" +
	"\aentries\x18\x02 \x03(\v2#.kafkamgmt.v1.SendMessageBatchEntryR\aentries\"W\n" +
	"\x10BatchResultEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x92\x01\n" +
	"\x18SendMessageBatchResponse\x12>\n" +
	"\n" +
	"successful\x18\x01 \x03(\v2\x1e.kafkamgmt.v1.BatchResultEntryR\n" +
	"successful\x126\n" +
	"\x06failed\x18\x02 \x03(\v2\x1e.kafkamgmt.v1.BatchResultEntryR\x06failed\"\xd5\x01\n" +
	"\x15ReceiveMessageRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x123\n" +
	"\x16max_number_of_messages\x18\x02 \x01(\x05R\x13maxNumberOfMessages\x12*\n" +
	"\x11wait_time_seconds\x18\x03 \x01(\x05R\x0fwaitTimeSeconds\x12<\n" +
	"\x1avisibility_timeout_seconds\x18\x04 \x01(\x05R\x18visibilityTimeoutSeconds\"\xb0\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ereceipt_handle\x18\x02 \x01(\tR\rreceiptHandle\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12?\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x1f.kafkamgmt.v1.MessageAttributesR\n" +
	"attributes\x12#\n" +
	"\rreceive_count\x18\x05 \x01(\x05R\freceiveCount\x12(\n" +
	"\x10message_group_id\x18\x06 \x01(\tR\x0emessageGroupId\x12;\n" +
	"\venqueued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\"K\n" +
	"\x16ReceiveMessageResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.kafkamgmt.v1.MessageR\bmessages\"\\\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12%\n" +
	"\x0ereceipt_handle\x18\x02 \x01(\tR\rreceiptHandle\"\x17\n" +
	"\x15DeleteMessageResponse\"P\n" +
	"\x17DeleteMessageBatchEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ereceipt_handle\x18\x02 \x01(\tR\rreceiptHandle\"{\n" +
	"\x19DeleteMessageBatchRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12?\n" +
	"\aentries\x18\x02 \x03(\v2%.kafkamgmt.v1.DeleteMessageBatchEntryR\aentries\"\x94\x01\n" +
	"\x1aDeleteMessageBatchResponse\x12>\n" +
	"\n" +
	"successful\x18\x01 \x03(\v2\x1e.kafkamgmt.v1.BatchResultEntryR\n" +
	"successful\x126\n" +
	"\x06failed\x18\x02 \x03(\v2\x1e.kafkamgmt.v1.BatchResultEntryR\x06failed\"\xa4\x01\n" +
	"\x1eChangeMessageVisibilityRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12%\n" +
	"\x0ereceipt_handle\x18\x02 \x01(\tR\rreceiptHandle\x12<\n" +
	"\x1avisibility_timeout_seconds\x18\x03 \x01(\x05R\x18visibilityTimeoutSeconds\"!\n" +
	"\x1fChangeMessageVisibilityResponse2\x9e\a\n" +
	"\fQueueService\x12\x7f\n" +
	"\vSendMessage\x12 .kafkamgmt.v1.SendMessageRequest\x1a!.kafkamgmt.v1.SendMessageResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/queues/{queue_name}/messages\x12\x94\x01\n" +
	"\x10SendMessageBatch\x12%.kafkamgmt.v1.SendMessageBatchRequest\x1a&.kafkamgmt.v1.SendMessageBatchResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/queues/{queue_name}/messages:batch\x12\x85\x01\n" +
	"\x0eReceiveMessage\x12#.kafkamgmt.v1.ReceiveMessageRequest\x1a$.kafkamgmt.v1.ReceiveMessageResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/queues/{queue_name}/messages\x12\x93\x01\n" +
	"\rDeleteMessage\x12\".kafkamgmt.v1.DeleteMessageRequest\x1a#.kafkamgmt.v1.DeleteMessageResponse\"9\x82\xd3\xe4\x93\x023*1/v1/queues/{queue_name}/messages/{receipt_handle}\x12\xa0\x01\n" +
	"\x12DeleteMessageBatch\x12'.kafkamgmt.v1.DeleteMessageBatchRequest\x1a(.kafkamgmt.v1.DeleteMessageBatchResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/v1/queues/{queue_name}/messages:batchDelete\x12\xb4\x01\n" +
	"\x17ChangeMessageVisibility\x12,.kafkamgmt.v1.ChangeMessageVisibilityRequest\x1a-.kafkamgmt.v1.ChangeMessageVisibilityResponse\"<\x82\xd3\xe4\x93\x026:\x01*21/v1/queues/{queue_name}/messages/{receipt_handle}BKZIgithub.com/rockliang/kafka-management-service/internal/api/v1;kafkamgmtv1b\x06proto3"

var (
	file_kafkamgmt_v1_queue_service_proto_rawDescOnce sync.Once
	file_kafkamgmt_v1_queue_service_proto_rawDescData []byte
)

func file_kafkamgmt_v1_queue_service_proto_rawDescGZIP() []byte {
	file_kafkamgmt_v1_queue_service_proto_rawDescOnce.Do(func() {
		file_kafkamgmt_v1_queue_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafkamgmt_v1_queue_service_proto_rawDesc), len(file_kafkamgmt_v1_queue_service_proto_rawDesc)))
	})
	return file_kafkamgmt_v1_queue_service_proto_rawDescData
}

var file_kafkamgmt_v1_queue_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_kafkamgmt_v1_queue_service_proto_goTypes = []any{
	(*MessageAttributes)(nil),               // 0: kafkamgmt.v1.MessageAttributes
	(*SendMessageRequest)(nil),              // 1: kafkamgmt.v1.SendMessageRequest
	(*SendMessageResponse)(nil),             // 2: kafkamgmt.v1.SendMessageResponse
	(*SendMessageBatchEntry)(nil),           // 3: kafkamgmt.v1.SendMessageBatchEntry
	(*SendMessageBatchRequest)(nil),         // 4: kafkamgmt.v1.SendMessageBatchRequest
	(*BatchResultEntry)(nil),                // 5: kafkamgmt.v1.BatchResultEntry
	(*SendMessageBatchResponse)(nil),        // 6: kafkamgmt.v1.SendMessageBatchResponse
	(*ReceiveMessageRequest)(nil),           // 7: kafkamgmt.v1.ReceiveMessageRequest
	(*Message)(nil),                         // 8: kafkamgmt.v1.Message
	(*ReceiveMessageResponse)(nil),          // 9: kafkamgmt.v1.ReceiveMessageResponse
	(*DeleteMessageRequest)(nil),            // 10: kafkamgmt.v1.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),           // 11: kafkamgmt.v1.DeleteMessageResponse
	(*DeleteMessageBatchEntry)(nil),         // 12: kafkamgmt.v1.DeleteMessageBatchEntry
	(*DeleteMessageBatchRequest)(nil),       // 13: kafkamgmt.v1.DeleteMessageBatchRequest
	(*DeleteMessageBatchResponse)(nil),      // 14: kafkamgmt.v1.DeleteMessageBatchResponse
	(*ChangeMessageVisibilityRequest)(nil),  // 15: kafkamgmt.v1.ChangeMessageVisibilityRequest
	(*ChangeMessageVisibilityResponse)(nil), // 16: kafkamgmt.v1.ChangeMessageVisibilityResponse
	nil,                                     // 17: kafkamgmt.v1.MessageAttributes.ValuesEntry
	(*timestamppb.Timestamp)(nil),           // 18: google.protobuf.Timestamp
}
var file_kafkamgmt_v1_queue_service_proto_depIdxs = []int32{
	17, // 0: kafkamgmt.v1.MessageAttributes.values:type_name -> kafkamgmt.v1.MessageAttributes.ValuesEntry
	0,  // 1: kafkamgmt.v1.SendMessageRequest.message_attributes:type_name -> kafkamgmt.v1.MessageAttributes
	0,  // 2: kafkamgmt.v1.SendMessageBatchEntry.message_attributes:type_name -> kafkamgmt.v1.MessageAttributes
	3,  // 3: kafkamgmt.v1.SendMessageBatchRequest.entries:type_name -> kafkamgmt.v1.SendMessageBatchEntry
	5,  // 4: kafkamgmt.v1.SendMessageBatchResponse.successful:type_name -> kafkamgmt.v1.BatchResultEntry
	5,  // 5: kafkamgmt.v1.SendMessageBatchResponse.failed:type_name -> kafkamgmt.v1.BatchResultEntry
	0,  // 6: kafkamgmt.v1.Message.attributes:type_name -> kafkamgmt.v1.MessageAttributes
	18, // 7: kafkamgmt.v1.Message.enqueued_at:type_name -> google.protobuf.Timestamp
	8,  // 8: kafkamgmt.v1.ReceiveMessageResponse.messages:type_name -> kafkamgmt.v1.Message
	12, // 9: kafkamgmt.v1.DeleteMessageBatchRequest.entries:type_name -> kafkamgmt.v1.DeleteMessageBatchEntry
	5,  // 10: kafkamgmt.v1.DeleteMessageBatchResponse.successful:type_name -> kafkamgmt.v1.BatchResultEntry
	5,  // 11: kafkamgmt.v1.DeleteMessageBatchResponse.failed:type_name -> kafkamgmt.v1.BatchResultEntry
	1,  // 12: kafkamgmt.v1.QueueService.SendMessage:input_type -> kafkamgmt.v1.SendMessageRequest
	4,  // 13: kafkamgmt.v1.QueueService.SendMessageBatch:input_type -> kafkamgmt.v1.SendMessageBatchRequest
	7,  // 14: kafkamgmt.v1.QueueService.ReceiveMessage:input_type -> kafkamgmt.v1.ReceiveMessageRequest
	10, // 15: kafkamgmt.v1.QueueService.DeleteMessage:input_type -> kafkamgmt.v1.DeleteMessageRequest
	13, // 16: kafkamgmt.v1.QueueService.DeleteMessageBatch:input_type -> kafkamgmt.v1.DeleteMessageBatchRequest
	15, // 17: kafkamgmt.v1.QueueService.ChangeMessageVisibility:input_type -> kafkamgmt.v1.ChangeMessageVisibilityRequest
	2,  // 18: kafkamgmt.v1.QueueService.SendMessage:output_type -> kafkamgmt.v1.SendMessageResponse
	6,  // 19: kafkamgmt.v1.QueueService.SendMessageBatch:output_type -> kafkamgmt.v1.SendMessageBatchResponse
	9,  // 20: kafkamgmt.v1.QueueService.ReceiveMessage:output_type -> kafkamgmt.v1.ReceiveMessageResponse
	11, // 21: kafkamgmt.v1.QueueService.DeleteMessage:output_type -> kafkamgmt.v1.DeleteMessageResponse
	14, // 22: kafkamgmt.v1.QueueService.DeleteMessageBatch:output_type -> kafkamgmt.v1.DeleteMessageBatchResponse
	16, // 23: kafkamgmt.v1.QueueService.ChangeMessageVisibility:output_type -> kafkamgmt.v1.ChangeMessageVisibilityResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_kafkamgmt_v1_queue_service_proto_init() }
func file_kafkamgmt_v1_queue_service_proto_init() {
	if File_kafkamgmt_v1_queue_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafkamgmt_v1_queue_service_proto_rawDesc), len(file_kafkamgmt_v1_queue_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kafkamgmt_v1_queue_service_proto_goTypes,
		DependencyIndexes: file_kafkamgmt_v1_queue_service_proto_depIdxs,
		MessageInfos:      file_kafkamgmt_v1_queue_service_proto_msgTypes,
	}.Build()
	File_kafkamgmt_v1_queue_service_proto = out.File
	file_kafkamgmt_v1_queue_service_proto_goTypes = nil
	file_kafkamgmt_v1_queue_service_proto_depIdxs = nil
}
